---
<%
driver = ENV.fetch('KITCHEN_DRIVER', 'vagrant')
if driver == 'docker' %>
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV.fetch('DOCKER_HOST', 'unix:///var/run/docker.sock') %>
  dns: <%= ENV.fetch('DNS_RESOLVER', '8.8.8.8') %>
<% else %>
driver:
  customize:
    memory: 2048
  name: vagrant
<% end %>

provisioner:
  name: puppet_apply
  modules_path: nevermind
  resolve_with_librarian_puppet: true
  require_chef_for_busser: true

<% if driver == 'docker' %>
platforms:
  - name: docker-centos6
    driver_plugin: docker
    driver_config:
      image: jlyheden/kitchen-puppet:centos6
      platform: centos
<% else %>
platforms:
  - name: centos6
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/centos-6.6-64-nocm
  - name: centos7
    driver_plugin: vagrant
    driver_config:
      box: centos/7
  - name: ubuntu1204
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/ubuntu-12.04-64-nocm
  - name: ubuntu1404
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/ubuntu-14.04-64-nocm
<% end %>

suites:
  - name: default
  - name: nexus3
